[[plugins]] # sidebar
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-e> :NERDTreeToggle<CR>
'''

[[plugins]] # wakatime
repo = 'wakatime/vim-wakatime'

[[plugins]] # autocomplete
repo = 'Shougo/deoplete.nvim'

[[plugins]] # git client
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [figitive] <Nop>
map <Leader>g [figitive]
nmap <silent> [figitive]s :<C-u>Gstatus<CR>
nmap <silent> [figitive]d :<C-u>Gdiff<CR>
nmap <silent> [figitive]b :<C-u>Gblame<CR>
nmap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]] # linter
repo = 'w0rp/ale'

[[plugins]] # linter c++
repo = 'neomake/neomake'
on_i = 1
hook_post_source = '''
autocmd! BufWritePost * Neomake
let g:neomake_cpp_enable_markers=['clang']
let g:neomake_cpp_clang_args = ["-std=c++14", "-Wall"]
let g:neomake_cpp_clangcheck_args = ["-std=c++14", "-Wall"]
'''

[[plugins]] # surround
repo = 'tpope/vim-surround'
