[[plugins]] # dein.vim command
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]] # sidebar
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-e> :NERDTreeToggle<CR>
'''

[[plugins]] # git client
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap [figitive] <Nop>
map <Leader>g [figitive]
nmap <silent> [figitive]s :<C-u>Gstatus<CR>
nmap <silent> [figitive]d :<C-u>Gdiff<CR>
nmap <silent> [figitive]b :<C-u>Gblame<CR>
nmap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]] # formatter
repo = 'rhysd/vim-clang-format'
hook_add = '''
let g:clang_format#auto_format = 1
let g:clang_format#code_style = 'llvm'
autocmd FileType c,cpp,cmake ClangFormatAutoEnable
'''
# on_ft = ['c', 'cpp', 'cmake']
