[[plugins]] # dein
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]] # autocomplete
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  set hidden
  let g:racer_cmd = expand('~/.cargo/bin/racer')
  let g:racer_experimental_completer = 1
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_source = '''
  let g:jedi#force_py_version = 3
'''
on_ft = 'python'

[[plugins]]
repo = "zchee/deoplete-clang"
on_ft = ['c', 'cpp', 'cmake']
depends = "deoplete.nvim"
hook_source = """
  let g:deoplete#sources#clang#libclang_path='/usr/lib/llvm-6.0/lib/libclang-6.0.so.1'
  let g:deoplete#sources#clang#clang_header='/usr/include/clang'
"""

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
depends = 'deoplete.nvim'
hook_source = '''
  let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]] # formatter
repo = "rhysd/vim-clang-format"
on_ft = ['c', 'cpp', 'cmake']
hook_add = '''
  let g:clang_format#auto_format = 1
  let g:clang_format#code_style = 'llvm'

  autocmd FileType c,cpp,cmake ClangFormatAutoEnable
  autocmd BufWritePre *.c,*.h,*.cpp :ClangFormat
'''

[[plugins]] # formatter
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
  autocmd BufWritePre *.rs :RustFmt
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'htmlcheetah', 'htmldjango', 'haml']
hook_add = '''
  let g:user_emmet_settings = {
  \  'variables' : {
  \    'lang' : "ja"
  \  },
  \  'html' : {
  \    'indentation' : '  ',
  \    'snippets' : {
  \      'html:5': "<!DOCTYPE html>\n"
  \        ."<html lang=\"${lang}\">\n"
  \        ."<head>\n"
  \        ."\t<meta charset=\"${charset}\">\n"
  \        ."\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
  \        ."\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
  \        ."\t<title></title>\n"
  \        ."</head>\n"
  \        ."<body>\n\t${child}|\n</body>\n"
  \        ."</html>",
  \    }
  \  }
  \}
'''
