[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # autocomplete
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_camel_case = 0
let g:deoplete#enable_ignore_case = 0
let g:deoplete#enable_refresh_always = 0
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#max_list = 10000
'''
on_i = 1

# [[plugins]] # C autocomplete
# repo = 'zchee/deoplete-clang'
# depends = ['deoplete']
# on_ft = ['c', 'cpp', 'cmake']
# hook_add = '''
# let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
# let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
# '''
# [[plugins]] # C autocomplete
# repo = 'justmao945/vim-clang'
# hook_add = '''
# let g:clang_c_options = '-std=gnu11'
# let g:clang_cpp_options = '-std=c++11 -stdlib=libc++'
# '''

# [[plugins]] # colorscheme
# repo = 'rakr/vim-one'
# hook_add = '''
# let g:one_allow_italics = 1 " I love italic for comments
# set background=dark
# " colorscheme の設定は source 後に行う必要があるので VimEnter で行う
# " ただし Colorscheme イベントの発生が抑制されないように nested をつける
# au MyAutoCmd VimEnter * nested colorscheme one
# '''

[[plugins]] # ステータスライン
repo = 'vim-airline/vim-airline'
hook_add = '''
" パワーラインでかっこよく
" let g:airline_powerline_fonts = 1
" タブバーをかっこよく
let g:airline#extensions#tabline#enabled = 1
" Lintツールによるエラー、警告を表示(ALEの拡張)
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#ale#error_symbol = 'E:'
let g:airline#extensions#ale#warning_symbol = 'W:'
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # wakatime
repo = 'wakatime/vim-wakatime'

[[plugins]] # Toml
repo = 'cespare/vim-toml'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]] # git diff
repo = 'airblade/vim-gitgutter'

[[plugins]] # プログラミング言語の強調表示など
repo = 'sheerun/vim-polyglot'
hook_add = '''
" Vue 効率的に強調
autocmd FileType vue syntax sync fromstart
'''

[[plugins]] # 閉じ括弧の補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # highlight color code
repo = 'lilydjwg/colorizer'

# [[plugins]] # typescript
# repo = 'mhartington/nvim-typescript'
# hook_add = '''
# let g:nvim_typescript#vue_support = 1
# '''

[[plugins]] # commentout
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
'''

[[plugins]] # cursor jump
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:easymotion_leader_key = '\<Space>'
'''

[[plugins]] # surround
repo = 'tpope/vim-surround'

[[plugins]] # bookmark
repo = 'MattesGroeger/vim-bookmarks'

[[plugins]] # linter
repo = 'w0rp/ale'
hook_add = '''
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 1
let g:ale_c_clang_options = ''
let g:ale_c_gcc_options = ''

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]] # vinary
repo = 'Shougo/vinarise'

[[plugins]] # ctrlp
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
'''

[[plugins]] # indent
repo = 'Yggdroot/indentLine'
