[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # hybrid
repo = 'joshdick/onedark.vim'
hook_add = '''
" "set background=dark
" colorscheme の設定は source 後に行う必要があるので VimEnter で行う
" ただし Colorscheme イベントの発生が抑制されないように nested をつける
au MyAutoCmd VimEnter * nested colorscheme onedark
'''

[[plugins]] # ステータスライン
repo = 'vim-airline/vim-airline'
hook_add = '''
" パワーラインでかっこよく
" let g:airline_powerline_fonts = 1
" タブバーをかっこよく
let g:airline#extensions#tabline#enabled = 1
" Lintツールによるエラー、警告を表示(ALEの拡張)
let g:airline#extensions#ale#enabled = 1
let g:airline#extensions#ale#error_symbol = 'E:'
let g:airline#extensions#ale#warning_symbol = 'W:'
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # wakatime
repo = 'wakatime/vim-wakatime'

[[plugins]] # Toml
repo = 'cespare/vim-toml'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja,en
'''

[[plugins]] # git diff
repo = 'airblade/vim-gitgutter'

[[plugins]] # プログラミング言語の強調表示など
repo = 'sheerun/vim-polyglot'
hook_add = '''
" Vue 効率的に強調
autocmd FileType vue syntax sync fromstart
'''

[[plugins]] # 閉じ括弧の補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # 文法チェッカ
repo = 'scrooloose/syntastic'

[[plugins]] # highlight color code
repo = 'lilydjwg/colorizer'

# [[plugins]] # typescript
# repo = 'mhartington/nvim-typescript'
# hook_add = '''
# let g:nvim_typescript#vue_support = 1
# '''

[[plugins]] # commentout
repo = 'scrooloose/nerdcommenter'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
'''

[[plugins]] # cursor jump
repo = 'easymotion/vim-easymotion'
hook_add = '''
let g:easymotion_leader_key = '\<Space>'
'''

[[plugins]] # surround
repo = 'tpope/vim-surround'
